### ISSUE TITLE
Beoordeling opdracht 1.2

### ISSUE THREAD

**Issue by Mennauu** [Ramon96/browser-technologies-1920#1]
Yo Ramon,

**Een beschrijving van alle features die je hebt getest**
Je geeft bijvoorbeeld bij _Kleurenblindheid_ aan dat er veel websites zijn die kunnen testen of je een goed contrast hebt. Ik zou dan graag willen weten welke websites/tools dat dan zijn. Evenals bij _Muis en trackpad_, hoe navigeer je dan wel door de website zonder de muis en trackpad?

Hoe ziet je websites er uit als je geen gebruikt maakt van afbeeldingen? Hij kan wel prima werken, maar ik zie graag de verschillen.

**Een beschrijving van de Devices en browsers waar je op hebt getest**
Het is duidelijk te lezen welke devices je hebt gebruikt om te testen. Ik kan alleen geen vergelijking maken met wat er wel of niet goed gaat, omdat er geen visueel beeld is. Hoe ziet je website er bijvoorbeeld uit als het filter wel werkt, en hoe ziet het eruit als het niet werkt? Afbeeldingen van de betreffende devices met daarop je website zou ook fijn zijn!

**Een beschrijving van de screenreader test**
Je beschrijving is te beknopt. Ookal ging er niet iets fout in je test, er zijn vast verbeterpunten te vinden of je kan juist noteren wat de screenreader goed deed. Wellicht een audiobestand toevoegen?

**Beschrijf hoe je de problemen hebt opgelost, of hoe je dit zou oplossen (met todo’s) als je genoeg tijd en budget zou hebben**
Je beschrijft overal netjes oplossingen.

--

Je beschrijvingen zijn te kort en je hebt geen afbeeldingen gebruikt. Ik adviseer je om te kijken naar de readme's van anderen, om inspiratie op te doen. Het moet echt nog een stuk beter!

**Comment by Ramon96** [comment]
Ik heb wat meer tekst hieraan toegevoegd. Helaas kan ik vanwege het  coronavirus geen foto's maken van de devices.
